fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.2.2"
    archive:
      repo: "git://github.com/voxpupuli/puppet-archive"
      ref: "v1.1.2"
    systemd:
      repo: "git://github.com/camptocamp/puppet-systemd.git"
      ref: "v0.4.0"
