fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.2.2"
    vault_client:
      repo: "git://github.com/puppernetes/module-vault_client"
      ref: "master"
