fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.17.1"
    concat:
      repo: "puppetlabs/concat"
      ref: "2.2.1"
    archive:
      repo: "puppet/archive"
      ref: "1.1.2"
