image: ruby:2.3

stages:
- test
- acceptance

lint:
  tags:
  - ruby-2.3
  - docker
  script:
  - bundle install --path /cache
  - bundle exec rake metadata_lint lint

validate:
  tags:
  - ruby-2.3
  - docker
  script:
  - bundle install --path /cache
  - bundle exec rake validate

spec:
  tags:
  - ruby-2.3
  - docker
  script:
  - bundle install --path /cache
  - bundle exec rake spec

beaker:
  stage: acceptance
  tags:
  - ruby-2.3
  - vagrant
  script:
  - bundle install
  - bundle exec rake beaker
