.test::puppet_module: &test_puppet_module
  stage: test
  tags:
  - docker
  script:
  - cd ${CI_PROJECT_DIR}/puppet
  - bundle install --path /cache
  - cd ${CI_PROJECT_DIR}/puppet/modules/${MODULE_NAME}
  - bundle exec rake test

# run test for puppet modules
test::puppet_module::aws_ebs:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: aws_ebs

test::puppet_module::calico:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: calico

test::puppet_module::etcd:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: etcd

test::puppet_module::kubernetes:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: kubernetes

test::puppet_module::kubernetes_addons:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: kubernetes_addons

test::puppet_module::prometheus:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: prometheus

test::puppet_module::tarmak:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: tarmak

test::puppet_module::vault_client:
  <<: *test_puppet_module
  variables:
    MODULE_NAME: vault_client

# run test on golang code
#
test::tarmak::golang:
  stage: test
  tags:
  - docker
  image: golang:1.8.3
  script:
  - rm -rf /go/src/github.com/jetstack
  - mkdir -p /go/src/github.com/jetstack
  - mv ${CI_PROJECT_DIR} /go/src/github.com/jetstack
  - cd /go/src/github.com/jetstack/tarmak
  - make all
  - mv /go/src/github.com/jetstack/tarmak ${CI_PROJECT_DIR}

stages:
- test
