# run test on golang code
#
test::tarmak::golang:
  stage: test
  tags:
  - docker
  image: golang:1.9.3
  script:
  - rm -rf /go/src/github.com/jetstack
  - mkdir -p /go/src/github.com/jetstack
  - mv ${CI_PROJECT_DIR} /go/src/github.com/jetstack
  - cd /go/src/github.com/jetstack/tarmak
  - make all
  - mv /go/src/github.com/jetstack/tarmak ${CI_PROJECT_DIR}

# run validation on terraform code
test::tarmak::terraform:
  stage: test
  tags:
  - docker
  services:
  - docker:dind
  image: docker:1.12
  script:
  - docker build -t tarmak-terraform:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID} terraform/
  - CONTAINER_ID=$(docker create tarmak-terraform:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID} /bin/sh -c "apk add --update make git && git init && git add .&& make verify")
  - docker cp terraform/ ${CONTAINER_ID}:/
  - docker start $CONTAINER_ID -a

# generate sphinx documentation
generate::docs:
  stage: test
  tags:
  - docker
  image: python:3
  script:
  - apt-get update
  - apt-get install -y python-enchant wbritish
  - pip install virtualenv
  - make -C docs spelling
  - make -C docs linkcheck
  - make -C docs html
  artifacts:
    paths:
    - docs/_build/html
    expire_in: 4 weeks

release::tarmak::puppet_publish_modules:
  stage: release
  tags:
  - docker
  only:
  - tags
  script:
  - cd ${CI_PROJECT_DIR}/puppet
  - bundle install --path /cache
  - echo "${PUPPETFORGE_DATA}" > ~/.puppetforge.yml && chmod 600 ~/.puppetforge.yml
  - bundle exec rake publish_modules

release::tarmak::golang:
  stage: release
  tags:
  - docker
  image: golang:1.9.3
  only:
  - tags
  script:
  - umask 0077
  - mkdir -p /root/.gnupg
  - echo "${GPG_PRIVATE_KEY}" | base64 -d > /root/.gnupg/secring.gpg
  - rm -rf /go/src/github.com/jetstack
  - mkdir -p /go/src/github.com/jetstack
  - mv ${CI_PROJECT_DIR} /go/src/github.com/jetstack
  - cd /go/src/github.com/jetstack/tarmak
  - make all
  - bin/goreleaser
  - mv /go/src/github.com/jetstack/tarmak ${CI_PROJECT_DIR}

stages:
- test
- acceptance
- release
