
stages:
- test
- acceptance

lint:
  image: ruby:2.3
  tags:
  - docker
  script:
  - bundle install --path /cache
  - bundle exec rake metadata_lint lint

validate:
  image: ruby:2.3
  tags:
  - docker
  script:
  - bundle install --path /cache
  - bundle exec rake validate

spec:
  image: ruby:2.3
  tags:
  - docker
  script:
  - bundle install --path /cache
  - bundle exec rake spec

beaker-three-node-cluster:
  stage: acceptance
  tags:
  - ruby-2.3
  - vagrant
  script:
  - bundle install
  - bundle exec rake beaker:3n-cluster
  only:
  - master

beaker-single-node:
  stage: acceptance
  tags:
  - ruby-2.3
  - vagrant
  script:
  - bundle install
  - bundle exec rake beaker:default
  only:
  - master
