builds:
  - main: ./cmd/wing/main.go
    binary: wing
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags: -tags netgo
  - main: ./cmd/tarmak/main.go
    binary: tarmak
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags: -tags netgo
archive:
  format: binary
release:
  github:
    owner: jetstack
    name: tarmak

gpg_signing:
  key_id: 9A1C42C8F5AA3CE6
