language: go
go:
  - 1.9
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install enchant
install:
  - make depend
  - make -C docs .venv
script:
  - make verify build
  - make -C docs spelling
  - make -C docs linkcheck
  - make -C docs html
