language: go
go:
  - 1.9
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install enchant
  - sudo curl -Lo /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
  - sudo chmod +x /usr/local/bin/dep
install:
  - make depend
  - make -C docs .venv
script:
  - make verify build
  - make -C docs spelling
  - make -C docs linkcheck
  - make -C docs html
