fixtures:
  symlinks:
    consul: "#{source_dir}"
    archive: "#{source_dir}/../archive"
    stdlib: "#{source_dir}/../stdlib"
    airworthy: "#{source_dir}/../airworthy"
    aws_ebs: "#{source_dir}/../aws_ebs"
