---
HOSTS:
  #  k8s-master:
  #    roles:
  #      - master
  #    platform: el-7-x86_64
  #    box: puppetlabs/centos-7.2-64-puppet
  #    hypervisor: vagrant
  #    ip: 10.123.0.21
  #  k8s-worker-1:
  #    roles:
  #      - worker
  #    platform: el-7-x86_64
  #    box: puppetlabs/centos-7.2-64-puppet
  #    hypervisor: vagrant
  #    ip: 11.123.0.22
  #  k8s-worker-2:
  #    roles:
  #      - worker
  #    platform: el-7-x86_64
  #    box: puppetlabs/centos-7.2-64-puppet
  #    hypervisor: vagrant
  #    ip: 11.123.0.23
  etcd-1:
    roles:
      - etcd
    platform: el-7-x86_64
    box: puppetlabs/centos-7.2-64-puppet
    hypervisor: vagrant
    ip: 10.123.0.11
    netmask: 255.255.255.0
  vault:
    roles:
      - vault
      - master
    platform: el-7-x86_64
    box: puppetlabs/centos-7.2-64-puppet
    hypervisor: vagrant
    ip: 10.123.0.12
    netmask: 255.255.255.0
CONFIG:
  type: foss
