---
HOSTS:
  #  k8s-master:
  #    roles:
  #      - master
  #    platform: el-7-x86_64
  #    box: puppetlabs/centos-7.2-64-puppet
  #    hypervisor: vagrant
  #    ip: 10.123.0.21
  #  k8s-worker-1:
  #    roles:
  #      - worker
  #    platform: el-7-x86_64
  #    box: puppetlabs/centos-7.2-64-puppet
  #    hypervisor: vagrant
  #    ip: 11.123.0.22
  #  k8s-worker-2:
  #    roles:
  #      - worker
  #    platform: el-7-x86_64
  #    box: puppetlabs/centos-7.2-64-puppet
  #    hypervisor: vagrant
  #    ip: 11.123.0.23
  etcd:
    roles:
      - etcd
    platform: el-7-x86_64
    box: puppetlabs/centos-7.2-64-puppet
    hypervisor: vagrant
    ip: 10.123.0.11
  #  vault:
  #    roles:
  #      - vault
  #    platform: el-7-x86_64
  #    box: puppetlabs/centos-7.2-64-puppet
  #    hypervisor: vagrant
  #    ip: 10.123.0.12
CONFIG:
  type: foss
